# Generated by Django 5.0.3 on 2026-05-23 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_api', '0002_initial'),
        ('projects_api', '0006_alter_finding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='analysis_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='projects_api.analysisrun'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='projects_api.finding'),
        ),
    ]
