# Generated by Django 5.0.3 on 2026-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_api', '0003_chatmessage_analysis_run_chatmessage_finding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'Użytkownik'), ('assistant', 'Asystent')], max_length=10),
        ),
    ]
