# Generated by Django 5.0.3 on 2026-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł sugestii')),
                ('description', models.TextField(verbose_name='Opis sugestii')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], default='medium', max_length=10, verbose_name='Priorytet')),
                ('status', models.CharField(choices=[('new', 'Nowa'), ('in_progress', 'W trakcie'), ('done', 'Zrealizowana')], default='new', max_length=15, verbose_name='Status')),
                ('recommendations', models.TextField(verbose_name='Rekomendacje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa projektu')),
                ('description', models.TextField(verbose_name='Opis projektu')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readability', models.TextField(blank=True, verbose_name='Czytelność (nazewnictwo, komentarze, formatowanie)')),
                ('structure', models.TextField(blank=True, verbose_name='Struktura kodu')),
                ('principles', models.TextField(blank=True, verbose_name='DRY / KISS / YAGNI')),
                ('modularity', models.TextField(blank=True, verbose_name='Modularność')),
                ('extensibility', models.TextField(blank=True, verbose_name='Rozszerzalność')),
                ('design_patterns', models.TextField(blank=True, verbose_name='Wzorce projektowe i spójność')),
                ('input_validation', models.TextField(blank=True, verbose_name='Walidacja danych wejściowych')),
                ('permission_management', models.TextField(blank=True, verbose_name='Zarządzanie uprawnieniami')),
                ('vulnerabilities', models.TextField(blank=True, verbose_name='Unikanie podatności (SQLi, XSS itp.)')),
                ('test_coverage', models.TextField(blank=True, verbose_name='Pokrycie testami')),
                ('test_quality', models.TextField(blank=True, verbose_name='Jakość testów')),
                ('test_automation', models.TextField(blank=True, verbose_name='Automatyzacja testów')),
                ('performance', models.TextField(blank=True, verbose_name='Złożoność / Efektywność')),
                ('comments_quality', models.TextField(blank=True, verbose_name='Komentarze w kodzie')),
                ('documentation', models.TextField(blank=True, verbose_name='README / dokumentacja techniczna')),
                ('installation_instructions', models.TextField(blank=True, verbose_name='Instrukcja uruchomienia')),
                ('coding_style', models.TextField(blank=True, verbose_name='Styl kodowania (PEP8 itp.)')),
                ('tools_usage', models.TextField(blank=True, verbose_name='CI/CD, lintery, formattery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
