# Generated by Django 5.0.3 on 2026-05-23 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='default_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='last_commit_sha',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, verbose_name='URL repozytorium GitHub'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis projektu'),
        ),
        migrations.CreateModel(
            name='RepositorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.PositiveIntegerField(default=0)),
                ('included_files', models.JSONField(blank=True, default=list)),
                ('ignored_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_snapshots', to='projects_api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
