# Generated by Django 5.0.3 on 2026-05-23 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0003_project_created_at_project_default_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ingesting', 'Ingesting'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('score_total', models.PositiveSmallIntegerField(default=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects_api.project')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to='projects_api.repositorysnapshot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ingesting', 'Ingesting'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_results', to='projects_api.analysisrun')),
            ],
            options={
                'ordering': ['agent_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True)),
                ('recommendation', models.TextField()),
                ('confidence', models.FloatField(default=0.8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='projects_api.analysisrun')),
            ],
            options={
                'ordering': ['severity', 'category', 'file_path', 'line_start', 'id'],
            },
        ),
    ]
