# Generated by Django 5.0.3 on 2026-05-23 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0004_analysisrun_agentresult_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentresult',
            name='model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agentresult',
            name='normalized_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentresult',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='finding',
            name='agent_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='finding',
            name='source',
            field=models.CharField(choices=[('tool', 'Tool'), ('ai', 'AI')], default='tool', max_length=20),
        ),
    ]
