# Generated by Django 5.0.3 on 2026-05-23 13:36

from django.db import migrations, models


def migrate_open_status_to_new(apps, schema_editor):
    Finding = apps.get_model("projects_api", "Finding")
    Finding.objects.filter(status="open").update(status="new")


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0005_agentresult_created_at_agentresult_model_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_open_status_to_new, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='new', max_length=20),
        ),
    ]
