# Generated by Django 5.0.3 on 2026-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0006_alter_finding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentresult',
            name='status',
            field=models.CharField(choices=[('queued', 'W kolejce'), ('ingesting', 'Indeksowanie'), ('analyzing', 'Analiza'), ('completed', 'Zakończony'), ('failed', 'Błąd')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('queued', 'W kolejce'), ('ingesting', 'Indeksowanie'), ('analyzing', 'Analiza'), ('completed', 'Zakończony'), ('failed', 'Błąd')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('critical', 'Krytyczne'), ('high', 'Wysokie'), ('medium', 'Średnie'), ('low', 'Niskie'), ('info', 'Informacyjne')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='source',
            field=models.CharField(choices=[('tool', 'Narzędzie'), ('ai', 'AI')], default='tool', max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('accepted', 'Zaakceptowane'), ('fixed', 'Naprawione'), ('ignored', 'Zignorowane')], default='new', max_length=20),
        ),
    ]
