# Generated by Django 5.0.3 on 2025-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_visit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='dormitory',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_community_member',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_receptionist',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
