# Generated by Django 5.0.3 on 2025-05-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_chatsession_message_delete_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readability', models.TextField(blank=True, verbose_name='Czytelność (nazewnictwo, komentarze, formatowanie)')),
                ('structure', models.TextField(blank=True, verbose_name='Struktura kodu')),
                ('principles', models.TextField(blank=True, verbose_name='DRY / KISS / YAGNI')),
                ('modularity', models.TextField(blank=True, verbose_name='Modularność')),
                ('extensibility', models.TextField(blank=True, verbose_name='Rozszerzalność')),
                ('design_patterns', models.TextField(blank=True, verbose_name='Wzorce projektowe i spójność')),
                ('input_validation', models.TextField(blank=True, verbose_name='Walidacja danych wejściowych')),
                ('permission_management', models.TextField(blank=True, verbose_name='Zarządzanie uprawnieniami')),
                ('vulnerabilities', models.TextField(blank=True, verbose_name='Unikanie podatności (SQLi, XSS itp.)')),
                ('test_coverage', models.TextField(blank=True, verbose_name='Pokrycie testami')),
                ('test_quality', models.TextField(blank=True, verbose_name='Jakość testów')),
                ('test_automation', models.TextField(blank=True, verbose_name='Automatyzacja testów')),
                ('performance', models.TextField(blank=True, verbose_name='Złożoność / Efektywność')),
                ('comments_quality', models.TextField(blank=True, verbose_name='Komentarze w kodzie')),
                ('documentation', models.TextField(blank=True, verbose_name='README / dokumentacja techniczna')),
                ('installation_instructions', models.TextField(blank=True, verbose_name='Instrukcja uruchomienia')),
                ('coding_style', models.TextField(blank=True, verbose_name='Styl kodowania (PEP8 itp.)')),
                ('tools_usage', models.TextField(blank=True, verbose_name='CI/CD, lintery, formattery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='user_api.project')),
            ],
        ),
    ]
