# Generated by Django 5.0.3 on 2025-05-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0013_projectanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł sugestii')),
                ('description', models.TextField(verbose_name='Opis sugestii')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], default='medium', max_length=10, verbose_name='Priorytet')),
                ('status', models.CharField(choices=[('new', 'Nowa'), ('in_progress', 'W trakcie'), ('done', 'Zrealizowana')], default='new', max_length=15, verbose_name='Status')),
                ('recommendations', models.JSONField(blank=True, null=True, verbose_name='Rekomendacje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='user_api.project')),
            ],
        ),
    ]
