# Generated by Django 5.0.3 on 2025-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0014_improvementsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementsuggestion',
            name='recommendations',
            field=models.TextField(verbose_name='Rekomendacje'),
        ),
    ]
